const CONTACTS = [
  {
    key: 1,
    name: '392 Jones',
    lang: 'English',
    email: 'lu_ben2002@yahoo.com',
    phone: '',
  },
  {
    key: 2,
    name: 'Auto Island Inc',
    lang: 'English',
    email: '',
    phone: '647-747-6109',
  },
  {
    key: 3,
    name: 'BITVO',
    lang: 'English',
    email: '42000023186@bitvodeposits.com',
    phone: '',
  },
  {
    key: 4,
    name: 'BITVO.COM',
    lang: 'English',
    email: 'noreply@bitvo.com',
    phone: '',
  },
  {
    key: 5,
    name: 'Chelsea Tough',
    lang: 'English',
    email: 'chelsea.tough@gmail.com',
    phone: '',
  },
  {
    key: 6,
    name: 'Christian',
    lang: 'English',
    email: 'pratt540@gmail.com',
    phone: '',
  },
  {
    key: 7,
    name: 'DnF',
    lang: 'English',
    email: 'franjessco@sympatico.ca',
    phone: '',
  },
  {
    key: 8,
    name: 'DUANE TOUGH',
    lang: 'English',
    email: 'dtough@hotmail.com',
    phone: '647-857-6694',
  },
  {
    key: 9,
    name: 'Gigadat',
    lang: 'English',
    email: 'etransfer@orderdeposit.com',
    phone: '',
  },
  {
    key: 10,
    name: 'J Grundy',
    lang: 'English',
    email: 'jegrundy@rogers.com',
    phone: '',
  },
  {
    key: 11,
    name: 'JJJ',
    lang: 'English',
    email: 'toughj@telus.net',
    phone: '',
  },
  {
    key: 12,
    name: 'Jon English',
    lang: 'English',
    email: 'john.oliverscoffee@gmail.com',
    phone: '',
  },
  {
    key: 13,
    name: 'Karen',
    lang: 'English',
    email: 'english_karen@yahoo.com',
    phone: '',
  },
  {
    key: 14,
    name: 'Mathew',
    lang: 'English',
    email: 'mathewm1212@gmail.com',
    phone: '',
  },
  {
    key: 15,
    name: 'Michael Sovereign Medical',
    lang: 'English',
    email: 'hello@sovereigncosmeticsurgery.com',
    phone: '',
  },
  {
    key: 16,
    name: 'Rishi',
    lang: 'English',
    email: 'rishi.jokhu@gmail.com',
    phone: '',
  },
  {
    key: 17,
    name: 'Robb MacDonald',
    lang: 'English',
    email: 'rm@lawintoronto.com',
    phone: '',
  },
  {
    key: 18,
    name: 'RobnGeo',
    lang: 'English',
    email: 'robngeo@gmail.com',
    phone: '',
  },
];

export default CONTACTS;
